# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/notebooks',
                'doc_host': 'https://notebooks.andrewlook.com',
                'git_url': 'https://github.com/andrewlook/notebooks',
                'lib_path': 'notebooks'},
  'syms': {}}
