project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Blog"
        href: blog/index.qmd
  sidebar: false

resources:
  - CNAME

metadata-files: [nbdev.yml, sidebar.yml]
