project:
  type: website

format:
  html:
    theme: litera
    css: styles.css
    toc: true

website:
  twitter-card:
    creator: "@andrewlook"
    site: "@andrewlook"
  open-graph: true
  repo-actions: [issue]
  navbar:
    logo: https://i.ibb.co/GxrvZ2T/CROP-oneline-a-stoke1-5.png
    title: andrew look
    search: true
    left:
      - text: "blog"
        href: blog/index.qmd
      - text: "jupyter"
        href: jupyter/index.qmd
      - text: "resume"
        href: resume/index.qmd
      - text: "about"
        href: about/index.qmd
    right:
      - icon: github
        text: "github"
        href: https://github.com/andrewlook
      - icon: instagram
        text: "instagram"
        href: https://instagram.com/andrewlookart
      - icon: twitter
        text: "twitter"
        href: https://twitter.com/andrewlook

  sidebar: false

resources:
  - CNAME

metadata-files: [nbdev.yml, sidebar.yml]
