project:
  type: website

format:
  html:
    theme: litera
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    logo: https://i.ibb.co/GxrvZ2T/CROP-oneline-a-stoke1-5.png
    title: andrew look
    search: true
    left:
      - text: "blog"
        href: blog/index.qmd
  sidebar: false

resources:
  - CNAME

metadata-files: [nbdev.yml, sidebar.yml]
