---
title: about me
page-layout: article
sidebar: false
toc: false
---

Hi, I'm Andrew Look.

I'm a machine learning engineer working on [Notion AI](https://www.notion.com/product/ai). I'm also an AI advisor at [Long Journey](https://www.longjourney.vc/), where I help startups think through how to build with AI and how to hire great technical talent. Previously I was CTO at URX (YC S'13, acquired by Pinterest) and Plato Design (YC S'13). In my spare time, I like to make art - painting, drawing, pottery. More recently I've been making audio-reactive visual LED/projector art for concerts with [Titanic's End](https://www.instagram.com/titanicsend/?hl=en).

### Work

I recently left my most recent startup, Aesthetic (Y Combinator Summer 2018).

Before that, I did ML engineering at Pinterest from 2016-2018.

Previously, I worked on a mobile ad startup called URX from 2013 until 2016 when [we](https://venturebeat.com/marketing/pinterest-buys-deep-linking-startup-urx/) [were](https://www.wsj.com/articles/pinterest-acquires-mobile-ad-startup-urx-1462298027) acquired by Pinterest.

### Side Projects

I'm also an AI advisor to [Long Journey Ventures](https://www.longjourney.vc/), occasionally helping with technical due diligence on companies with an AI/ML focus.

In spare time, I'm building audio-reactive digital art and training new team members as Head of Software for the [Titanic's End](https://github.com/titanicsend/LXStudio-TE) [Mutant Vehicle](https://www.instagram.com/titanicsend/).

### Art

I've been [painting](https://www.instagram.com/p/BZv08oaH4T8/?img_index=1) since 2013 (when I really needed a [hobby](https://www.instagram.com/p/BHFRHzNAB_y/) to [unwind](https://www.instagram.com/p/7GvJ0ak61s/) from the [stress](https://www.instagram.com/p/18k93Rk67V/) of startup life).

I've been experimenting with ML art and generative AI since 2016 (when I started playing with DeepDreams and GANs and [making](https://www.instagram.com/p/BTCIo5HhuJ5/) [physical](https://www.instagram.com/p/BZkhq4AH2va/) [paintings](https://www.instagram.com/p/BvdIQK3gUyM/) from the [outputs](https://www.instagram.com/p/BHtOyhLAkBj/)).

I've been making [single](https://www.instagram.com/p/B7Z1VMnAUnG/)-[line](https://www.instagram.com/p/B7KZ1BlADiB/) [drawings](https://www.instagram.com/p/CDRxJLwswYZ/) since 2018 (when I decided to [experiment](https://www.instagram.com/p/BpKxLh4lAtg/) with adding a [constraint](https://www.instagram.com/p/BpPXWjoFWkS/) to my art practice).

I've been making pottery since 2022 (when I wanted to experiment with making art in three dimensions rather than two).
